- name: catalogue setup
  hosts: CATALOGUE
  become: yes
  tags: catalogue
  roles:
    - catalogue







#- name: rabbitmq setup
#  hosts: RABBITMQ
#  become: yes
#  tags: rabbitmq
#  roles:
#    - rabbitmq


#- name: frontend setup
#  hosts: FRONTEND
#  become: yes
#  tags: frontend
#  roles:
#    - frontend

