- name: rabbitmq setup
  hosts: RABBITMQ
  become: yes
  tags: rabbitmq
  roles:
    - rabbitmq


#- name: frontend setup
#  hosts: FRONTEND
#  become: yes
#  tags: frontend
#  roles:
#    - frontend

