
#  # rm -rf frontend-master static README.md
#  # mv localhost.conf /etc/nginx/default.d/roboshop.conf
#  Finally restart the service once to effect the changes.
#
## systemctl restart nginx

- name: Frontend install
  ansible.builtin.yum:
    name: nginx
    state: installed

- name: download and unzip
  ansible.builtin.import_role:
    name: common
    tasks_from: download

- name: Remove file (delete file)
  ansible.builtin.file:
    path: /usr/share/nginx/html/
    state: absent

- name: Copy file with owner and permissions
  ansible.builtin.copy:
    src: /tmp/frontend-main/static/
    dest: /usr/share/nginx/html/
    remote_src: yes

- name: docking roboshop.cnf
  ansible.builtin.copy:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf

- name: Start Nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: yes