- name: Installing maven
  ansible.builtin.yum:
    name: maven
    state: installed

- name: app user setup and unzipping
  import_role:
    name: common
    tasks_from: app_user-setup

- name: Running mvn clean
  shell: "mvn clean install"

#
#- name: renameing the service file
#  shell: mv /home/roboshop/{{COMPONENT}}-main /home/roboshop/{{COMPONENT}}
#  remote_src: yes
#- name:







## yum install maven -y
#As per the standard process, we always run the applications as a normal user.
#Create a user
#
#  # useradd roboshop
#Download the repo
#$ cd /home/roboshop
#$ curl -s -L -o /tmp/shipping.zip "https://github.com/roboshop-devops-project/shipping/archive/main.zip"
#$ unzip /tmp/shipping.zip
#$ mv shipping-main shipping
#$ cd shipping
#$ mvn clean package
#$ mv target/shipping-1.0.jar shipping.jar
#Update Servers IP address in /home/roboshop/shipping/systemd.service
#
#Copy the service file and start the service.
#
## mv /home/roboshop/shipping/systemd.service /etc/systemd/system/shipping.service
## systemctl daemon-reload
## systemctl start shipping
## systemctl enable shipping
