- name: Installing maven
  ansible.builtin.yum:
    name: maven
    state: installed

- name: app user setup and unzipping
  ansible.builtin.import_role:
    name: common
    tasks_from: app_user-setup

- name: installation of dependencies
  ansible.builtin.shell:
    name: mvn clean package && mv /target/{{COMPONENT}}-1.0.jar shipping.jar
  args:
    chdir: /home/roboshop/shipping
  become_user: roboshop

- name: rename the content
  ansible.builtin.shell:
    name: mv /home/roboshop/shipping/target/shipping-1.0.jar /home/roboshop/shipping/targetshipping.jar

- name: app user setup and unzipping
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd.yml
