- name: Adding roboshop user
  ansible.builtin.user:
    name: roboshop

- name: download and unzip
  ansible.builtin.import_role:
    name: common
    tasks_from: download

- name: removing existing directory
  ansible.builtin.file:
    src: /home/roboshop/{{COMPONENT}}
    state: absent

- name: Copy file with owner and permissions
  ansible.builtin.copy:
    src: /tmp/{{COMPONENT}}-main/
    dest: /home/roboshop/{{COMPONENT}}/
    remote_src: yes
    become_user: roboshop
