#- name: download and unzip
#  ansible.builtin.unarchive:
#    src: http://nexus.roboshop.internal:8081/repository/{{COMPONENT}}/{{COMPONENT}}.{{gitTag}}.zip
#    dest: /tmp/
#    remote_src: yes


- name: Downloading artifactory
  ansible.builtin.get_url:
    src: http://nexus1.roboshop.internal:8081/repository/{{COMPONENT}}/{{COMPONENT}}.{{gitTag}}.zip
    dest: /tmp/
    username: admin
    password: "{{ NEXUS_PSW }}"