- name: installing nodejs
  ansible.builtin.yum:
    name:
      - nodejs
      - make
      - gcc-c++
    state: installed
- name: start

- name: application user setup and download
  import_tasks: app_user-setup.yml

- name: installing npm
  community.general.npm:
    path: /home/roboshop/{{COMPONENT}}
  become_user: roboshop

- name: systemd setup and starting
  import_tasks: systemd.yml
