- name: Update {{COMPONENT}} SystemD file
  ansible.builtin.template:
    src: systemd.service
    dest: /etc/systemd/system/{{COMPONENT}}.service

- name: enable a timer for dnf-automatic
  systemd:
    name: {{COMPONENT}}
    state: restarted
    enabled: True