- name: Update {{COMPONENT}} SystemD file
  ansible.builtin.template:
    src: systemd.service
    dest: /etc/systemd/system/{{COMPONENT}}.service

- name: service enabled and started
  systemd:
    name: "{{COMPONENT}}"
    state: restarted
    enabled: True