- name: repository file of mongod
  ansible.builtin.copy:
    src: rabbitm.repo
    dest: /etc/yum.repos.d/rabbitmq.repo
- name: installation of rabbitmq
  ansible.builtin.yum:
    name: rabbitmq-server

- name: systemd start for rabbitmq
   ansible.builtin.systemd:
     name: rabbitmq-server
     state: started
     enabled: yes

- community.rabbitmq.rabbitmq_user:
    user: roboshop
    password: roboshop123
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present
