- name: Adding repo file
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: installing mongod
  ansible.builtin.yum:
    name: mongodb-org
    state: installed

- name: replacing config file
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: starting application
  ansible.builtin.import_role:
    name: common
    tasks_from: start_service

- name: unzipping content
  ansible.builtin.import_role:
    name: common
    tasks_from: unzipping

- name: loading schema
  ansible.builtin.shell:
    name:
      - mongo < catalogue.js
      - mongo < users.js
    chdir: /etc/mongod-main/

