- name: Adding repo file
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: installing mongod
  ansible.builtin.yum:
    name: mongodb-org
    state: installed

- name: replacing config file
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: starting application
  ansible.builtin.systemd:
    name: mongod
    state: restarted
    enabled: yes


- name: unzipping content
  ansible.builtin.import_role:
    name: common
    tasks_from: unzipping

- name: Load Schema
  community.mongodb.mongodb_shell:
    file: "/tmp/mongodb-main/{{item}}.js"
    idempotent: yes
  loop:
    - catalogue
    - users