- name: Add repository
  yum_repository:
    name: mongod.repo
    baseurl: https://raw.githubusercontent.com/roboshop-devops-project/mongod/main/mongo.repo

- name: installing mongod
  ansible.builtin.yum:
    name: mongod-org
    state: installed

- name: replacing config file
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: starting application
  ansible.builtin.import_role:
    name: common
    tasks_from: start_service

- name: unzipping content
  ansible.builtin.import_role:
    name: common
    tasks_from: unzipping

- name: loading schema
  ansible.builtin.shell:
    name:
      - mongo < catalogue.js
      - mongo < users.js
    chdir: /etc/mongod-main/

