- name: installing nodejs
  asnible.builtin.yum:
    name:
      - nodejs
      - make
      - gcc-c++
    state: installed

- name: Adding roboshop user
  ansible.builtin.user:
    name: roboshop

- name: download and unzip
  ansible.builtin.unarchive:
    src: https://github.com/roboshop-devops-project/{{COMPONENT}}/archive/main.zip
    dest: /tmp/
    remote_src: yes

- name: removing existing directory
  ansible.builtin.file:
  src: /home/roboshop/catalogue
state: absent

- name: Copy file with owner and permissions
  ansible.builtin.copy:
    src: /tmp/catalogue-main/
    dest: /home/roboshop/catalogue/
    remote_src: yes
    become_user: roboshop

-- name: Installation of npm
  npm:
    name: npm
    path: /home/roboshop/catalogue/



#  $ mv catalogue-main catalogue
#  $ cd /home/roboshop/catalogue
#  $ npm install
#NOTE: We need to update the IP address of MONGODB Server in systemd.service file
#  Now, lets set up the service with systemctl.
#
## mv /home/roboshop/catalogue/systemd.service /etc/systemd/system/catalogue.service
## systemctl daemon-reload
## systemctl start catalogue
## systemctl enable catalogue
