- name: instaling python and apps
  ansible.builtin.yum:
    name:
      - python36
      - gcc
      - python3-devel

- name: application user add
  ansible.builtin.import_role:
    name: common
    tasks_from: app_user

- name: application user add
  ansible.builtin.import_role:
    name: common
    tasks_from: download


- name: application user add
  ansible.builtin.import_role:
    name: common
    tasks_from: unzipping

- name: Install specified python requirements
  pip:
    requirements: /home/roboshop/payment/requirements.txt
    executable: pip3

- name: app user details
  ansible.builtin.debug:
    msg: "{{app_user_info}}"

- name: replace line user
  ansible.builtin.lineinfile:
      path: /home/roboshop/{{COMPONENT}}/{{COMPONENT}}.ini
      regexp: '^uid'
      line: uid = {{app_user_info.uid}}

- name: replace line group
  ansible.builtin.lineinfile:
      path: /home/roboshop/{{COMPONENT}}/{{COMPONENT}}.ini
      regexp: '^gid'
      line: gid = {{app_user_info.group}}


- name: daemon load and start service
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd.service

