- name: when conditon
  hosts: localhost
  vars:
    abc: ABC
  tasks:
    - name: printing sample1
      when: abc == "ABC"
      debug:
        msg: "sample 1"
    - name: printing sample2
      when: abc == "abc"
      debug:
        msg: "abc var = abc"
