#- name: frontend setup
#  hosts: FRONTEND
#  become: yes
#  roles:
#    - frontend

#- name: mongod setup
#  hosts: MONGOD
#  become: yes
#  roles:
#    - mongod
##
#- name: catalogue setup
#  hosts: CATALOGUE
#  become: yes
#  roles:
#    - catalogue

#- name: rabbitmq setup
#  hosts: RABBITMQ
#  become: yes
#  roles:
#    - rabbitmq
#
#- name: redis setup
#  hosts: REDIS
#  become: yes
#  roles:
#    - redis
#
#- name: user-setup
#  hosts: USER
#  become: yes
#  roles:
#    - user
#
#- name: cart-setup
#  hosts: CART
#  become: yes
#  roles:
#    - cart

- name: rabbitmq
  hosts: RABBITMQ
  become: yes
  roles:
    - rabbitmq
